basePath: /api/wikis
definitions:
  model.Wiki:
    properties:
      category:
        type: string
      description:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
host: localhost:8001
info:
  contact: {}
  description: API documentation for the Wiki Service.
  title: Wiki Service API
  version: "1.0"
paths:
  /api/wikis/:
    get:
      description: Retrieves the list of all wiki JSON objects from the database.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Wiki'
            type: array
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get all wikis
      tags:
      - Wikis
    post:
      consumes:
      - application/json
      description: Creates a new wiki. Expects a JSON object in the request body.
      parameters:
      - description: Wiki information
        in: body
        name: wiki
        required: true
        schema:
          $ref: '#/definitions/model.Wiki'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Wiki'
        "400":
          description: Invalid request body
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Create a new wiki
      tags:
      - Wikis
  /api/wikis/category:
    get:
      description: Retrieves wikis under the given category.
      parameters:
      - description: Category to search
        in: query
        name: category
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Wiki'
            type: array
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get wikis by category
      tags:
      - Wikis
  /api/wikis/description:
    get:
      description: Retrieves wikis that match the given description.
      parameters:
      - description: Description to search
        in: query
        name: description
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Wiki'
            type: array
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get wikis by description
      tags:
      - Wikis
  /api/wikis/exactTitle:
    get:
      description: Retrieves wiki that matches the given title.
      parameters:
      - description: Title to search
        in: query
        name: title
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Wiki'
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get wiki by exact title
      tags:
      - Wikis
  /api/wikis/health:
    get:
      description: Checks if the service is up
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health Check
      tags:
      - Health
  /api/wikis/id/:
    delete:
      description: Deletes a wiki by its ID.
      parameters:
      - description: Wiki ID
        in: query
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "400":
          description: Invalid ID
          schema:
            type: string
        "404":
          description: Wiki not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Delete a wiki by ID
      tags:
      - Wikis
    get:
      description: Retrieves a wiki by its ID.
      parameters:
      - description: Wiki ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Wiki'
        "400":
          description: Invalid ID
          schema:
            type: string
        "404":
          description: Wiki not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get a wiki by ID
      tags:
      - Wikis
    put:
      consumes:
      - application/json
      description: Updates a wiki by its ID. Expects a JSON object in the request.
      parameters:
      - description: Wiki ID
        in: query
        name: id
        required: true
        type: string
      - description: Updated wiki information
        in: body
        name: wiki
        required: true
        schema:
          $ref: '#/definitions/model.Wiki'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Wiki'
        "400":
          description: Invalid ID or request body
          schema:
            type: string
        "404":
          description: Wiki not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Update a wiki by ID
      tags:
      - Wikis
  /api/wikis/title:
    get:
      description: Retrieves the list of all wikis that matches the title.
      parameters:
      - description: Title to search
        in: query
        name: title
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Wiki'
            type: array
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get all wikis by title.
      tags:
      - Wikis
swagger: "2.0"
