[global]
API_GATEWAY_URL = "http://localhost:8000"
FRONTEND_URL = "http://localhost"
PRETTY_LOGS = true
DEBUG = true
DB_NAME = "laWikiCopia2"
MONGODB_URI = ""
JWT_SECRET = ""
MAILSENDER_API_KEY = ""
MAILSENDER_DOMAIN = ""
MAILSENDER_NAME = ""

[gateway]
PORT = 8000
WIKI_SERVICE_URL = "http://localhost:8001"
ENTRY_SERVICE_URL = "http://localhost:8002"
COMMENT_SERVICE_URL = "http://localhost:8003"
VERSION_SERVICE_URL = "http://localhost:8005"
AUTH_SERVICE_URL = "http://localhost:8080"
MEDIA_SERVICE_URL = "http://localhost:8081"
TRANSLATION_SERVICE_URL = "http://localhost:8082"

[wiki]
PORT = 8001
DB_COLLECTION_NAME = "wikis"

[entry]
PORT = 8002
DB_COLLECTION_NAME = "entradas"

[comment]
PORT = 8003
DB_COLLECTION_NAME = "comentarios"

[version]
PORT = 8005
DB_COLLECTION_NAME = "versiones"

[auth]
PORT = 8080
GOOGLE_OAUTH_CLIENT_ID = ""
GOOGLE_OAUTH_CLIENT_SECRET = ""
GOOGLE_OAUTH_REDIRECT_URL = ""
DB_COLLECTION_NAME = "usuarios"

[media]
PORT = 8081
CLOUDIFY_CLOUD_NAME = ""
CLOUDIFY_API_KEY = ""
CLOUDIFY_API_SECRET = ""
DB_COLLECTION_NAME = "media"

[translation]
PORT = 8082
DEEPL_KEY = ""
