[gateway]
PORT = 8000
WIKI_SERVICE_URL = "http://wiki-service:8001"
ENTRY_SERVICE_URL = "http://entry-service:8002"
COMMENT_SERVICE_URL = "http://comment-service:8003"
AUTH_SERVICE_URL = "http://auth-service:8004"
VERSION_SERVICE_URL = "http://version-service:8005"
PRETTY_LOGS = true
DEBUG = true

[wiki]
PORT = 8001
MONGODB_URI = ""
DB_COLLECTION_NAME = "wikis"
DB_NAME = "laWiki"
PRETTY_LOGS = true
DEBUG = true

[entry]
PORT = 8002
MONGODB_URI = ""
DB_COLLECTION_NAME = "entradas"
DB_NAME = "laWiki"
PRETTY_LOGS = true
DEBUG = true

[comment]
PORT = 8003
MONGODB_URI = ""
DB_COLLECTION_NAME = "comentarios"
DB_NAME = "laWiki"
PRETTY_LOGS = true
DEBUG = true

[auth]
PORT = 8004
GOOGLE_OAUTH_CLIENT_ID = ""
GOOGLE_OAUTH_CLIENT_SECRET = ""
GOOGLE_OAUTH_REDIRECT_URL = ""
JWT_SECRET = ""
PRETTY_LOGS = true
DEBUG = true

[version]
PORT = 8005
MONGODB_URI = ""
DB_COLLECTION_NAME = "versiones"
DB_NAME = "laWiki"
PRETTY_LOGS = true
DEBUG = true
