basePath: /api/auth
host: localhost:8080
info:
  contact: {}
  description: API documentation for the Auth Service. !!THIS SERVICE IS WIP!!
  title: Auth Service API
  version: "1.0"
paths:
  /api/auth/callback:
    get:
      description: Handles the OAuth2 callback from Google
      parameters:
      - description: OAuth state
        in: query
        name: state
        required: true
        type: string
      - description: Authorization code
        in: query
        name: code
        required: true
        type: string
      responses:
        "302":
          description: Redirect after login
          schema:
            type: string
        "401":
          description: Invalid OAuth state
          schema:
            type: string
        "500":
          description: Could not create JWT
          schema:
            type: string
      summary: OAuth2 Callback
      tags:
      - Authentication
  /api/auth/health:
    get:
      description: Checks if the service is up
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health Check
      tags:
      - Health
  /api/auth/login:
    get:
      description: Initiates the OAuth2 flow with Google
      responses:
        "302":
          description: Redirect to Google OAuth2 login
          schema:
            type: string
      summary: Initiate OAuth2 Login
      tags:
      - Authentication
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  OAuth2:
    authorizationUrl: https://accounts.google.com/o/oauth2/auth
    flow: accessCode
    tokenUrl: https://oauth2.googleapis.com/token
    type: oauth2
swagger: "2.0"
